services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    security_opt:
      - label=disable
    environment:
      DOMAIN: "https://vaultwarden.sasvat.me"
    volumes:
      - ./vw-data/:/data/:Z

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vaultwarden.rule=Host(`vaultwarden.sasvat.me`)"
      - "traefik.http.routers.vaultwarden.entrypoints=websecure"
      - "traefik.http.routers.vaultwarden.tls.certresolver=le"
      - "traefik.http.services.vaultwarden.loadbalancer.server.port=80"

    networks:
      - traefik_net
networks:
    traefik_net:
        external: true
