services:

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - label=type:spc_t

    ports:
      - "127.0.0.1:31080:80"
      - "127.0.0.1:31443:443"

    volumes:
      - /run/user/1002/podman/podman.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml
      - ./letsencrypt:/letsencrypt

    networks:
      - traefik_net


  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: always

    networks:
      - traefik_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.sasvat.me`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true
