services:

  traefik:
    image: traefik
    container_name: traefik
    restart: always

    command:
      - --configFile=/etc/traefik/traefik.yml

    ports:
      - "31080:31080"
      - "31443:31443"
      - "8080:8080"

    volumes:
      - /run/user/1001/podman/podman.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./letsencrypt:/letsencrypt

    networks:
      - traefik_net


  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: always

    networks:
      - traefik_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.sasvat.me`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"

networks:
  traefik_net:
    external: true
