services:

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - label=type:spc_t

    ports:
      - "127.0.0.1:31080:80"
      - "127.0.0.1:31443:443"

    volumes:
      - /run/user/1002/podman/podman.sock:/var/run/docker.sock:ro # Docker socket
      - ./traefik.yml:/traefik.yml
      - ./letsencrypt:/letsencrypt
      - ./logs:/var/log/traefik

    networks:
      - traefik_net


  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: always

    networks:
      - traefik_net

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.sasvat.me`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=le"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      #Middleware for crowdsec configuration
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec.Enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec.CrowdsecMode=live"
      # Points to the container name in the other file across the shared network
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec.CrowdsecLapiHost=crowdsec:8080"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec.CrowdsecLapiScheme=http"
      - "traefik.http.middlewares.crowdsec.plugin.crowdsec.CrowdsecLapiKey=YOUR_GENERATED_KEY"
      
      # Apply Middleware
      - "traefik.http.routers.whoami.middlewares=crowdsec"

networks:
  traefik_net:
    external: true
