services:

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: always
    security_opt:
      - label=disable

    depends_on:
      - redis
      - db

    volumes:
      - ./data:/var/www/html:Z

    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db

    networks:
      - nextcloud
      - traefik_net

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.nextcloud.rule=Host(`cloud.sasvat.me`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls.certresolver=le"

      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"


  db:
    image: mariadb:lts
    container_name: nextcloud-db
    restart: always
    security_opt:
      - label=disable

    command: --transaction-isolation=READ-COMMITTED

    volumes:
      - ./db:/var/lib/mysql:Z

    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

    networks:
      - nextcloud


  redis:
    image: redis:7
    container_name: nextcloud-redis
    restart: always
    security_opt:
      - label=disable

    networks:
      - nextcloud


networks:
  nextcloud:
  traefik_net:
    external: true