services:
  whatsupdocker:
    image: getwud/wud:latest
    container_name: wud
    restart: unless-stopped

    environment:
      - WUD_AUTH_ADMIN_USER=admin
      - WUD_AUTH_ADMIN_PASSWORD=MySecurePassword123

    volumes:
      - /run/user/1002/podman/podman.sock:/var/run/docker.sock:Z

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wud.rule=Host(`wud.sasvat.me`)"
      - "traefik.http.routers.wud.entrypoints=websecure"
      - "traefik.http.routers.wud.tls.certresolver=le"
      - "traefik.http.services.wud.loadbalancer.server.port=3000"

    networks:
      - traefik_net

networks:
  traefik_net:
    external: true
