services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        restart: always
        security_opt:
            - label=disable

        volumes:
            - ./config:/config
            - ./cache:/cache

            - type: bind
              source: ./movies
              target: /movies
              read_only: true
            
            - type: bind
              source: ./series
              target: /series
              read_only: true
        environment:
            - JELLYFIN_PublishedServerUrl=https://jellyfin.sasvat.me
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.sasvat.me`)"
            - "traefik.http.routers.jellyfin.entrypoints=websecure"
            - "traefik.http.routers.jellyfin.tls.certresolver=le"
            - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
            - "traefik.http.routers.jellyfin.middlewares=crowdsec-bouncer@file"
        networks:
            - traefik_net
networks:
    traefik_net:
        external: true
