services:
    jellyfin:
        image: jellyfin/jellyfin:latest
        container_name: jellyfin
        restart: always
        security_opt:
            - label=disable

        volumes:
            - ./config:/config
            - ./cache:/cache

            - type: bind
              source: ./movies
              target: /movies
              read_only: true
            
            - type: bind
              source: ./series
              target: /series
              read_only: true
        environment:
            - JELLYFIN_PublishedServerUrl=https://jellyfin.sasvat.me
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.sasvat.me`)"
            - "traefik.http.routers.jellyfin.entrypoints=websecure"
            - "traefik.http.routers.jellyfin.tls.certresolver=le"
            - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
            - "traefik.http.routers.jellyfin.middlewares=crowdsec-bouncer@file"
        networks:
            - traefik_net
            - media_net

    radarr:
        image: lscr.io/linuxserver/radarr:latest
        container_name: radarr
        restart: unless-stopped

        security_opt:
            - label=disable

        environment:
            - PUID=1002
            - PGID=1002
            - TZ=Asia/Kolkata

        volumes:
            - ./radarr:/config
            - ./:/data

        networks:
            - media_net
            - traefik_net

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.radarr.rule=Host(`radarr.sasvat.me`)"
            - "traefik.http.routers.radarr.entrypoints=websecure"
            - "traefik.http.routers.radarr.tls.certresolver=le"
            - "traefik.http.services.radarr.loadbalancer.server.port=7878"
            - "traefik.http.routers.radarr.middlewares=crowdsec-bouncer@file"

    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        container_name: qbittorrent
        restart: unless-stopped

        security_opt:
            - label=disable

        environment:
            - PUID=1002
            - PGID=1002
            - TZ=Asia/Kolkata
            - WEBUI_PORT=8080

        volumes:
            - ./qbittorrent:/config
            - ./:/data

        networks:
            - media_net
            - traefik_net

        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.sasvat.me`)"
            - "traefik.http.routers.qbittorrent.entrypoints=websecure"
            - "traefik.http.routers.qbittorrent.tls.certresolver=le"
            - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
            - "traefik.http.routers.qbittorrent.middlewares=crowdsec-bouncer@file"
networks:
    traefik_net:
        external: true
    media_net:
        external: true
