services:
  metube:
    image: ghcr.io/alexta69/metube:latest
    container_name: metube
    restart: always
    security_opt:
      - label=disable

    volumes:
      - ./downloads:/downloads:Z

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.metube.rule=Host(`metube.sasvat.me`)"
      - "traefik.http.routers.metube.entrypoints=websecure"
      - "traefik.http.routers.metube.tls.certresolver=letsencrypt"
      - "traefik.http.services.metube.loadbalancer.server.port=8081"

    networks:
      - traefik_net
networks:
  traefik_net:
    external: true